openai:
  api-key: ${GPT_API_KEY}
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLI}
            client-secret: ${GOOGLE_PASS}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - profile     #이름, 프로필 이미지
              - email       #이메일
        provider:
          google:
            user-name-attribute: sub
  config:
    import: optional:file:.env[.properties]
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false
  application:
    name: nextValue
  datasource:
    url: jdbc:h2:tcp://localhost/~/testJPA2
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect  # MySQL8Dialect ?? MySQLDialect ??

jwt:
  secret-key: ${SECRET_KEY}
auth:
  token:
    hmacSecretBase64: ${SECRET_KEY} #토큰 서명키
    accessTtlSec: 120000 #20분 배포후 10분으로 변경가능
#fcm:
#  service-account-path: classpath:firebase/memento_fcm_key.json
#
#openai:

#  api-key: ${OPENAI_API_KEY}

